name = "TrixiLW"
uuid = "448c043f-8f12-4619-bfac-a47248cda7f8"
authors = ["Arpit-Babbar <arpitbabbar@gmail.com>"]
version = "0.1.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"
